# set verbosity
/control/verbose 2
/run/verbose 2
/tracking/verbose 0

# output path
/inputs/output_file ./output/neutrons.root 

# initialize run
/run/initialize
/random/setSeeds 0 31

/process/had/rdm/nucleusLimits 39 39 18 18

/gps/particle neutron

#source whole LAr volume
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 115 300 180 cm
/gps/pos/halfx 115 cm
/gps/pos/halfy 300 cm
/gps/pos/halfz 180 cm

# angular distribution
/gps/ang/type iso

# energy distribution
/gps/ene/type Mono
/gps/ene/mono 0.025 eV

# run
/run/beamOn 50000
