
# set verbosity
/control/verbose 1
/run/verbose 1
/tracking/verbose 0

# configure supernova
/inputs/particle_type SUPERNOVA

# output path
/inputs/output_file ./output/radiogenic_Ar39_background.root

# initialize run
/run/initialize
/random/setSeeds 137 100

# event ID offset
/event/offset 0

# Supernova configs
/supernova/Event_Window 10 s
/supernova/Event_Cutoff 10 s

/supernova/N_Ar39_Decays 1

/process/had/rdm/nucleusLimits 39 39 18 18

# run
/run/beamOn 10000

